export const LEDGER_EVENT_TYPES = {
  ISSUE_ZEN: 'ISSUE_ZEN',
  APPLY_ZEN: 'APPLY_ZEN',
  EXPIRE_ZEN: 'EXPIRE_ZEN',
  EXTEND_ZEN_EXPIRY: 'EXTEND_ZEN_EXPIRY',
  LOCK_ZEN: 'LOCK_ZEN',
  UNLOCK_ZEN: 'UNLOCK_ZEN',
  ISSUE_ZEN_PLUS: 'ISSUE_ZEN_PLUS',
  LOCK_ZEN_PLUS: 'LOCK_ZEN_PLUS',
  UNLOCK_ZEN_PLUS: 'UNLOCK_ZEN_PLUS',
  MISSION_REWARD: 'MISSION_REWARD',
  ACCRUE_CIRCULATION_FEE: 'ACCRUE_CIRCULATION_FEE',
  ACCRUE_DIGITAL_ASSET_FEE: 'ACCRUE_DIGITAL_ASSET_FEE',
  TRANSFER_TO_COMMON_RESERVE: 'TRANSFER_TO_COMMON_RESERVE',
  ADJUSTMENT: 'ADJUSTMENT',
  TRANSFER_ZEN: 'TRANSFER_ZEN',
  ISSUE_ZEN_FROM_COMMON_RESERVE: 'ISSUE_ZEN_FROM_COMMON_RESERVE',
} as const

export type LedgerEventType = keyof typeof LEDGER_EVENT_TYPES

export const EVENT_LABELS_JA: Record<string, string> = {
  ISSUE_ZEN: 'Zen発行',
  APPLY_ZEN: 'Zen使用',
  EXPIRE_ZEN: 'Zen失効',
  EXTEND_ZEN_EXPIRY: 'Zen期限延長',
  LOCK_ZEN: 'Zenロック',
  UNLOCK_ZEN: 'Zenロック解除',
  ISSUE_ZEN_PLUS: 'Zen+獲得',
  LOCK_ZEN_PLUS: 'Zen+ロック',
  UNLOCK_ZEN_PLUS: 'Zen+ロック解除',
  MISSION_REWARD: 'ミッション報酬',
  ACCRUE_CIRCULATION_FEE: '縁環料記録',
  ACCRUE_DIGITAL_ASSET_FEE: 'デジタル資産手数料記録',
  TRANSFER_TO_COMMON_RESERVE: '共通プール還流',
  ADJUSTMENT: '訂正記録',
  TRANSFER_ZEN: 'Zen移転',
  ISSUE_ZEN_FROM_COMMON_RESERVE: '共通プールからZen発行',
}
